import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Banner from "@/components/Banner";
import ProductFeed from "@/components/ProductFeed";
import PropTypes,{ InferProps }  from 'prop-types';

const inter = Inter({ subsets: ["latin"] });

interface Props {
  products: [],
}

export default function Home({products}: Props) {

 
  return (
    <div className="bg-gray-100">
      <Head>
        <title>Amazon clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* header */}
      <Header />
      <main className="max-w-screen-2xl mx-auto">
        {/* banner */}
        <Banner />

        {/* product field */}
        <ProductFeed products={products}/>
      </main>
    </div>
  );
}



export async function getServerSideProps(context:any) {
  const products = await fetch("https://fakestoreapi.com/products").then(
    (res) => res.json()
  );

  return {
    props:{
      products,
    },
  }
}
